<a href="https://colab.research.google.com/github/MUQSEED961/Credit-Delinquency-Prediction-and-Dashboard/blob/main/Tata_intership.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
delinquency = pd.read_csv("/content/delinquency_dataset_colab_tata.csv")

In [ ]:
delinquency.head()

Customer_ID   Age    Income  Credit_Score  Credit_Utilization  \
0    CUST0001  56.0  165580.0         398.0            0.390502   
1    CUST0002  69.0  100999.0         493.0            0.312444   
2    CUST0003  46.0  188416.0         500.0            0.359930   
3    CUST0004  32.0  101672.0         413.0            0.371400   
4    CUST0005  60.0   38524.0         487.0            0.234716   

   Missed_Payments  Delinquent_Account  Loan_Balance  Debt_to_Income_Ratio  \
0              3.0                 0.0       16310.0              0.317396   
1              6.0                 1.0       17401.0              0.196093   
2              0.0                 0.0       13761.0              0.301655   
3              3.0                 0.0       88778.0              0.264794   
4              2.0                 0.0       13316.0              0.510583   

  Employment_Status  Account_Tenure Credit_Card_Type     Location Month_1  \
0               EMP            18.0          Student  Los Angeles    Late   
1     Self-employed             0.0         Standard      Phoenix  Missed   
2     Self-employed             1.0         Platinum      Chicago  Missed   
3        Unemployed            15.0         Platinum      Phoenix    Late   
4     Self-employed            11.0         Standard      Phoenix  Missed   

   Month_2 Month_3  Month_4  Month_5  Month_6  
0     Late  Missed     Late   Missed     Late  
1   Missed    Late   Missed  On-time  On-time  
2     Late    Late  On-time   Missed     Late  
3   Missed    Late   Missed     Late     Late  
4  On-time  Missed     Late     Late     Late

In [ ]:
delinquency.isnull().sum()

Customer_ID              0
Age                      0
Income                  39
Credit_Score             2
Credit_Utilization       0
Missed_Payments          0
Delinquent_Account       0
Loan_Balance            29
Debt_to_Income_Ratio     0
Employment_Status        0
Account_Tenure           0
Credit_Card_Type         0
Location                 0
Month_1                  0
Month_2                  0
Month_3                  0
Month_4                  0
Month_5                  0
Month_6                  0
dtype: int64

In [ ]:
delinquency['Income']=delinquency['Income'].fillna(delinquency['Income'].median())
delinquency['Credit_Score']=delinquency['Credit_Score'].fillna(delinquency['Credit_Score'].median())


In [ ]:
delinquency['Loan_Balance']=delinquency['Loan_Balance'].fillna(delinquency["Loan_Balance"].median())

In [ ]:
delinquency.dtypes

Customer_ID              object
Age                     float64
Income                  float64
Credit_Score            float64
Credit_Utilization      float64
Missed_Payments         float64
Delinquent_Account      float64
Loan_Balance            float64
Debt_to_Income_Ratio    float64
Employment_Status        object
Account_Tenure          float64
Credit_Card_Type         object
Location                 object
Month_1                  object
Month_2                  object
Month_3                  object
Month_4                  object
Month_5                  object
Month_6                  object
dtype: object

In [ ]:
x = delinquency.drop(['Customer_ID','Employment_Status','Credit_Card_Type','Delinquent_Account','Location','Month_1','Month_2','Month_3','Month_4','Month_5','Month_6'],axis=1)
y=delinquency['Delinquent_Account']

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
X_scale = StandardScaler()

In [ ]:
X_scale

StandardScaler()

In [ ]:
X_scaled=X_scale.fit_transform(x)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_trian,x_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.2,random_state=45,stratify=y)

In [ ]:
from sklearn.linear_model import LogisticRegression

Logictic Regression

In [ ]:
model=LogisticRegression(class_weight='balanced')

In [ ]:
model

LogisticRegression(class_weight='balanced')

In [ ]:
model.fit(x_trian,y_train)

LogisticRegression(class_weight='balanced')

In [ ]:
y_pred_log = model.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,f1_score,roc_auc_score,accuracy_score

In [ ]:
confusion_matrix(y_test,y_pred_log)

array([[33, 51],
       [ 9,  7]])

In [ ]:
f1_log=f1_score(y_test,y_pred_log)
f1_log

0.1891891891891892

In [ ]:
auc_log=roc_auc_score(y_test,y_pred_log)
auc_log

np.float64(0.41517857142857145)

In [ ]:
acc_log = accuracy_score(y_test,y_pred_log)
acc_log

0.4

Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model_rf=RandomForestClassifier(class_weight='balanced')

In [ ]:
model_rf

RandomForestClassifier(class_weight='balanced')

In [ ]:
model_rf.fit(x_trian,y_train)

RandomForestClassifier(class_weight='balanced')

In [ ]:
# Step 1: Get probabilities
y_prob_rf = model.predict_proba(x_test)[:,1]

# Step 2: Apply custom threshold
y_pred_rf = (y_prob_rf > 0.5).astype(int)


In [ ]:
confusion_matrix(y_test,y_pred_rf)

array([[33, 51],
       [ 9,  7]])

In [ ]:
auc_rf = roc_auc_score(y_test,y_prob_rf)

In [ ]:
auc_rf

np.float64(0.38913690476190477)

In [ ]:
f1_rf=f1_score(y_test,y_pred_rf)
f1_rf

0.1891891891891892

In [ ]:
acc_rf=accuracy_score(y_test,y_pred_rf)
acc_rf

0.4

XGBoost

In [ ]:
from xgboost import XGBClassifier

In [ ]:
model_xgb = XGBClassifier(n_estimators=200,max_depth=5,random_state=45)

In [ ]:
model_xgb

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=200,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
model_xgb.fit(x_trian,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=200,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
y_prob_xgb = model_xgb.predict_proba(x_test)[:,1]

y_pred_xgb = (y_prob_xgb > 0.1).astype(int)   # start with 0.4 threshold


In [ ]:
auc_xgb=roc_auc_score(y_test,y_prob_xgb)
auc_xgb

np.float64(0.39806547619047616)

In [ ]:
f1_xgb=f1_score(y_test,y_pred_xgb)
f1_xgb

0.09523809523809523

In [ ]:
acc_xgb=accuracy_score(y_test,y_pred_xgb)
acc_xgb

0.62

In [ ]:
confusion_matrix(y_test,y_pred_xgb)

array([[60, 24],
       [14,  2]])

GradientBoosting

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
model_gbr = GradientBoostingClassifier(n_estimators=200,max_depth=10,random_state=45)

In [ ]:
model_gbr.fit(x_trian,y_train)

GradientBoostingClassifier(max_depth=10, n_estimators=200, random_state=45)

In [ ]:
y_prob_gbc = model_xgb.predict_proba(x_test)[:,1]

y_pred_gbc = (y_prob_gbc > 0.1).astype(int)   # start with 0.4 threshold


In [ ]:
acc_gbc=accuracy_score(y_test,y_pred_gbc)
acc_gbc

0.62

In [ ]:
confusion_matrix(y_test,y_pred_gbc)

array([[60, 24],
       [14,  2]])

In [ ]:
f1_gbc=f1_score(y_test,y_pred_gbc)
f1_gbc

0.09523809523809523

In [ ]:
auc_gbc=roc_auc_score(y_test,y_prob_gbc)
auc_gbc

np.float64(0.39806547619047616)

In [ ]:
metrics_df = pd.DataFrame({
    "Model": ["Logistic", "Random Forest", "XGBoost", "Gradient Boost"],
    "Accuracy": [acc_log, acc_rf, acc_xgb, acc_gbc],
    "F1 Score": [f1_log, f1_rf, f1_xgb, f1_gbc],
    "AUC": [auc_log, auc_rf, auc_xgb, auc_gbc]
})


In [ ]:
metrics_df

Model  Accuracy  F1 Score       AUC
0        Logistic      0.40  0.189189  0.415179
1   Random Forest      0.40  0.189189  0.389137
2         XGBoost      0.62  0.095238  0.398065
3  Gradient Boost      0.62  0.095238  0.398065

In [ ]:
metrics_df.to_csv("model_metrics.csv", index=False)